CREATE PROCEDURE [dbo].addCfql2Answer
@ParticipantName varchar(64),
@ParticipantAge int,
@DateOfBirth date,
@Sex varchar(64),
@InformantName varchar(64),
@InformantAge int,
@DateOfSurvey date,
@InformantRelationshipToPatient varchar(64),
@ParticipantDiagnosis varchar(64),
@ParticipantAgeDiagnosis int,
@ParticipantDiagosisSeverity varchar (64),
@ChildQol1 int,
@ChildQol2 int,
@ChildQol3 int,
@ChildQol4 int,
@ChildQolAverage decimal(5,2), 
@FamilyQol5 int,
@FamilyQol6 int,
@FamilyQol7 int,
@FamilyQol8 int,
@FamilyQolAverage decimal(5,2), 
@CaregiverQol9 int,
@CaregiverQol10 int,
@CaregiverQol11 int,
@CaregiverQol12 int,
@CaregiverQolAverage decimal(5,2), 
@FinancialQol13 int,
@FinancialQol14 int,
@FinancialQol15 int,
@FinancialQolAverage decimal(5,2), 
@SocialNetworkQol16 int,
@SocialNetworkQol17 int,
@SocialNetworkQol18 int,
@SocialNetworkQol19 int,
@SocialNetworkQolAverage decimal(5,2), 
@PartnerRelationshipQolSpouse varchar(3),
@PartnerRelationshipQolSpouseRelation varchar(64),
@PartnerRelationshipQol20 int,
@PartnerRelationshipQol21 int,
@PartnerRelationshipQol22 int,
@PartnerRelationshipQol23 int,
@PartnerRelationshipQolAverage decimal(5,2), 
@CopingQol24 int,
@CopingQol25 int,
@CopingQol26 int,
@CopingQolAverage decimal(5,2), 
@CumulativeScore decimal(5,2)
AS
INSERT INTO [dbo].CFQL2
VALUES (
@ParticipantName,
@ParticipantAge,
@DateOfBirth,
@Sex,
@InformantName,
@InformantAge,
@DateOfSurvey,
@InformantRelationshipToPatient,
@ParticipantDiagnosis,
@ParticipantAgeDiagnosis,
@ParticipantDiagosisSeverity,
@ChildQol1,
@ChildQol2,
@ChildQol3,
@ChildQol4,
@ChildQolAverage, 
@FamilyQol5,
@FamilyQol6,
@FamilyQol7,
@FamilyQol8,
@FamilyQolAverage, 
@CaregiverQol9,
@CaregiverQol10,
@CaregiverQol11,
@CaregiverQol12,
@CaregiverQolAverage, 
@FinancialQol13,
@FinancialQol14,
@FinancialQol15,
@FinancialQolAverage, 
@SocialNetworkQol16,
@SocialNetworkQol17,
@SocialNetworkQol18,
@SocialNetworkQol19,
@SocialNetworkQolAverage, 
@PartnerRelationshipQolSpouse,
@PartnerRelationshipQolSpouseRelation,
@PartnerRelationshipQol20,
@PartnerRelationshipQol21,
@PartnerRelationshipQol22,
@PartnerRelationshipQol23,
@PartnerRelationshipQolAverage, 
@CopingQol24,
@CopingQol25,
@CopingQol26,
@CopingQolAverage, 
@CumulativeScore)
GO