CREATE PROCEDURE [dbo].addCfql2Answer
@ParticipantName varchar(64),
@ParticipantAge int,
@DateOfBirth date,
@Sex varchar(64),
@InformantName varchar(64),
@InformantAge int,
@DateOfSurvey date,
@InformantRelationshipToPatient varchar(64),
@ParticipantDiagnosis varchar(64),
@ParticipantAgeDiagnosis int,
@ParticipantDiagosisSeverity varchar (64),
@ChildQol1 int,
@ChildQol2 int,
@ChildQol3 int,
@ChildQol4 int,
@ChildQolAverage decimal(5,2), 
@FamilyQol5 int,
@FamilyQol6 int,
@FamilyQol7 int,
@FamilyQol8 int,
@FamilyQolAverage decimal(5,2), 
@CaregiverQol9 int,
@CaregiverQol10 int,
@CaregiverQol11 int,
@CaregiverQol12 int,
@CaregiverQolAverage decimal(5,2), 
@FinancialQol13 int,
@FinancialQol14 int,
@FinancialQol15 int,
@FinancialQolAverage decimal(5,2), 
@SocialNetworkQol16 int,
@SocialNetworkQol17 int,
@SocialNetworkQol18 int,
@SocialNetworkQol19 int,
@SocialNetworkQolAverage decimal(5,2), 
@PartnerRelationshipQolSpouse varchar(3),
@PartnerRelationshipQolSpouseRelation varchar(64),
@PartnerRelationshipQol20 int,
@PartnerRelationshipQol21 int,
@PartnerRelationshipQol22 int,
@PartnerRelationshipQol23 int,
@PartnerRelationshipQolAverage decimal(5,2), 
@CopingQol24 int,
@CopingQol25 int,
@CopingQol26 int,
@CopingQolAverage decimal(5,2), 
@CumulativeScore decimal(5,2)
AS
INSERT INTO [dbo].CFQL2
VALUES (
@ParticipantName,
@ParticipantAge,
@DateOfBirth,
@Sex,
@InformantName,
@InformantAge,
@DateOfSurvey,
@InformantRelationshipToPatient,
@ParticipantDiagnosis,
@ParticipantAgeDiagnosis,
@ParticipantDiagosisSeverity,
@ChildQol1,
@ChildQol2,
@ChildQol3,
@ChildQol4,
@ChildQolAverage, 
@FamilyQol5,
@FamilyQol6,
@FamilyQol7,
@FamilyQol8,
@FamilyQolAverage, 
@CaregiverQol9,
@CaregiverQol10,
@CaregiverQol11,
@CaregiverQol12,
@CaregiverQolAverage, 
@FinancialQol13,
@FinancialQol14,
@FinancialQol15,
@FinancialQolAverage, 
@SocialNetworkQol16,
@SocialNetworkQol17,
@SocialNetworkQol18,
@SocialNetworkQol19,
@SocialNetworkQolAverage, 
@PartnerRelationshipQolSpouse,
@PartnerRelationshipQolSpouseRelation,
@PartnerRelationshipQol20,
@PartnerRelationshipQol21,
@PartnerRelationshipQol22,
@PartnerRelationshipQol23,
@PartnerRelationshipQolAverage, 
@CopingQol24,
@CopingQol25,
@CopingQol26,
@CopingQolAverage, 
@CumulativeScore
)
GO

CREATE PROCEDURE [dbo].addAsdq2Answer
@ParticipantName varchar(64),
@ParticipantAge int,
@DateOfBirth date,
@Sex varchar(64),
@InformantName varchar(64),
@InformantAge int,
@DateOfSurvey date,
@InformantRelationshipToPatient varchar(64),
@ParticipantDiagnosis varchar(64),
@ParticipantAgeDiagnosis int,
@ParticipantDiagosisSeverity varchar (64),
@Q1 int,
@Q2 int,
@Q3 int,
@Q4 int,
@Q5 int,
@Q6 int,
@Q7 int,
@Q8 int,
@Q9 int,
@Q10 int,
@Q11 int,
@Q12 int,
@Q13 int,
@Q14 int,
@Q15 int,
@Q16 int,
@Q17 int,
@Q18 int,
@Q19 int,
@Q20 int,
@Q21 int,
@Q22 int,
@Q23 int,
@Q24 int,
@Q25 int,
@Q26 int,
@Q27 int,
@Q28 int,
@Q29 int,
@Q30 int,
@Q31 int,
@Q32 int,
@Q33 int,
@Q34 int,
@Q35 int,
@Q36 int,
@Q37 int,
@Q38 int,
@Q39 int,
@SCISubscore decimal(5,2),
@RRBSubscore decimal(5,2),
@SocialMotivationSubscore decimal(5,2),
@NonVervalCommunicationSubscore decimal(5,2),
@ReciprocitySubscore decimal(5,2),
@PerspectiveTakingSubscore decimal(5,2),
@RelationshipsSubscore decimal(5,2),
@RepetitiveBehaviorSubscore decimal(5,2),
@NeedForSamenessSubscore decimal(5,2),
@SensorySenstivitySubscore decimal(5,2),
@SensoryInterestsSubscore decimal(5,2),
@RestrictedInterestsSubscore decimal(5,2),
@CumulativeScore decimal(5,2)
AS
INSERT INTO [dbo].ASDQ2
VALUES (
@ParticipantName,
@ParticipantAge,
@DateOfBirth,
@Sex,
@InformantName,
@InformantAge,
@DateOfSurvey,
@InformantRelationshipToPatient,
@ParticipantDiagnosis,
@ParticipantAgeDiagnosis,
@ParticipantDiagosisSeverity,
@Q1,
@Q2,
@Q3,
@Q4,
@Q5,
@Q6,
@Q7,
@Q8,
@Q9,
@Q10,
@Q11,
@Q12,
@Q13,
@Q14,
@Q15,
@Q16,
@Q17,
@Q18,
@Q19,
@Q20,
@Q21,
@Q22,
@Q23,
@Q24,
@Q25,
@Q26,
@Q27,
@Q28,
@Q29,
@Q30,
@Q31,
@Q32,
@Q33,
@Q34,
@Q35,
@Q36,
@Q37,
@Q38,
@Q39
)
GO

CREATE PROCEDURE [dbo].addSurveyInformation
@UniqueId varchar(64),
@CFQL2Selected varchar(1),
@ASDQ2Selected varchar(1),
@PhysicianFirstName varchar(64),
@PhysicianLastName varchar(64),
@RequesterEmail varchar(64),
@RecicipientEmail varchar(64)
AS
INSERT INTO [dbo].SurveyInformation
VALUES (
@UniqueId,
@CFQL2Selected,
@ASDQ2Selected,
@PhysicianFirstName,
@PhysicianLastName,
@RequesterEmail,
@RecicipientEmail
)
GO
